name: PC application build
on: [push]

env:
    QT_VERSION: '5.14.2'

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          version: ${{env.QT_VERSION}}
      - name: Build
        run: |
          & "./scripts/vcpkg/get_mumble_dependencies.ps1"
          cmake --build . 
        working-directory: ./
        shell: powershell
